spring:
  redis:
    host: 192.168.1.79
    port: 6379
    database: 0


knife4j:
  application-title: agileway examples
  base-package: com.jn.agileway.redis.examples.controller

agileway:
  redis:
    global-template:
      enabled: true
      key:
        prefix: agileway_redis_test

  rest:
    global-response-body:
      base-packages: com.jn.agileway.redis.examples.controller
